module: imagedeid
pacs_ip: host.docker.internal
pacs_port: 4242
pacs_aet: ORTHANC
acc_col: acc
ctp_filters: |
  !ImageType.contains("INVALID") +
  !InstanceNumber.equals("1")
ctp_anonymizer: |
  <script>
      <p t="SITENAME">SiteName</p>
      <p t="SITEID">1</p>
      <p t="DATEINC">-3210</p>
      <p t="UIDROOT">1.2.840.113654.2.70.1</p>

      <!-- To keep -->
      <e en="T" t="00080005" n="SpecificCharacterSet">@keep()</e>
      <e en="T" t="00080016" n="SOPClassUID">@keep()</e>
      <e en="T" t="00080030" n="StudyTime">@keep()</e>
      <e en="T" t="00080031" n="SeriesTime">@keep()</e>
      <e en="T" t="00080032" n="AcquisitionTime">@keep()</e>
      <e en="T" t="00080033" n="ContentTime">@keep()</e>
      <e en="T" t="00080034" n="OverlayTime">@keep()</e>
      <e en="T" t="00080035" n="CurveTime">@keep()</e>
      <e en="T" t="00080070" n="Manufacturer">@keep()</e>
      <e en="T" t="0008103e" n="SeriesDescription">@keep()</e>
      <e en="T" t="00081090" n="ManufacturerModelName">@keep()</e>
      <e en="T" t="00081150" n="RefSOPClassUID">@keep()</e>
      <e en="T" t="00100040" n="PatientSex">@keep()</e>
      <e en="T" t="00101010" n="PatientAge">@keep()</e>
      <e en="T" t="00101020" n="PatientSize">@keep()</e>
      <e en="T" t="00101030" n="PatientWeight">@keep()</e>
      <e en="T" t="00102160" n="EthnicGroup">@keep()</e>
      <e en="T" t="001021a0" n="SmokingStatus">@keep()</e>
      <e en="T" t="001021c0" n="PregnancyStatus">@keep()</e>
      <e en="T" t="00102203" n="PatientSexNeutered">@keep()</e>
      <e en="T" t="00180015" n="BodyPartExamined">@keep()</e>
      <e en="T" t="00181000" n="DeviceSerialNumber">@keep()</e>
      <e en="T" t="00181002" n="DeviceUID">@keep()</e>
      <e en="T" t="00181004" n="PlateID">@keep()</e>
      <e en="T" t="00181005" n="GeneratorID">@keep()</e>
      <e en="T" t="00181007" n="CassetteID">@keep()</e>
      <e en="T" t="00181008" n="GantryID">@keep()</e>
      <e en="T" t="00181020" n="SoftwareVersion">@keep()</e>
      <e en="T" t="0018700a" n="DetectorID">@keep()</e>
      <e en="T" t="00280301" n="BurnedInAnnotation">@keep()</e>
      <e en="T" t="00321001" n="ScheduledStudyStartTime">@keep()</e>
      <e en="T" t="00321011" n="ScheduledStudyStopTime">@keep()</e>
      <e en="T" t="00380021" n="AdmittingTime">@keep()</e>
      <e en="T" t="00380032" n="DischargeTime">@keep()</e>
      <e en="T" t="00400003" n="SPSStartTime">@keep()</e>
      <e en="T" t="00400005" n="SPSEndTime">@keep()</e>
      <e en="T" t="00400245" n="PPSStartTime">@keep()</e>
      <e en="T" t="00080060" n="Modality">@keep()</e>

      <!-- To date shift -->
      <e en="T" t="00080012" n="InstanceCreationDate">@incrementdate(this,@DATEINC)</e>
      <e en="T" t="00080020" n="StudyDate">@incrementdate(this,@DATEINC)</e>
      <e en="T" t="00080021" n="SeriesDate">@incrementdate(this,@DATEINC)</e>
      <e en="T" t="00080022" n="AcquisitionDate">@incrementdate(this,@DATEINC)</e>
      <e en="T" t="00080023" n="ContentDate">@incrementdate(this,@DATEINC)</e>
      <e en="T" t="00080024" n="OverlayDate">@incrementdate(this,@DATEINC)</e>
      <e en="T" t="00080025" n="CurveDate">@incrementdate(this,@DATEINC)</e>
      <e en="T" t="0008002a" n="AcquisitionDatetime">@incrementdate(this,@DATEINC)</e>
      <e en="T" t="001021d0" n="LastMenstrualDate">@incrementdate(this,@DATEINC)</e>
      <e en="T" t="00181012" n="DateOfSecondaryCapture">@incrementdate(this,@DATEINC)</e>
      <e en="T" t="00181078" n="Radiopharmaceutical Start DateTime">@incrementdate(this,@DATEINC)</e>
      <e en="T" t="00181079" n="Radiopharmaceutical Stop DateTime">@incrementdate(this,@DATEINC)</e>
      <e en="T" t="00181200" n="DateOfLastCalibration">@incrementdate(this,@DATEINC)</e>
      <e en="T" t="0018700c" n="DateOfLastDetectorCalibration">@incrementdate(this,@DATEINC)</e>
      <e en="T" t="00321000" n="ScheduledStudyStartDate">@incrementdate(this,@DATEINC)</e>
      <e en="T" t="00321010" n="ScheduledStudyStopDate">@incrementdate(this,@DATEINC)</e>
      <e en="T" t="00321040" n="StudyArrivalDate">@incrementdate(this,@DATEINC)</e>
      <e en="T" t="00321050" n="StudyCompletionDate">@incrementdate(this,@DATEINC)</e>
      <e en="T" t="00380020" n="AdmittingDate">@incrementdate(this,@DATEINC)</e>
      <e en="T" t="00380030" n="DischargeDate">@incrementdate(this,@DATEINC)</e>
      <e en="T" t="00400002" n="SPSStartDate">@incrementdate(this,@DATEINC)</e>
      <e en="T" t="00400004" n="SPSEndDate">@incrementdate(this,@DATEINC)</e>
      <e en="T" t="00400244" n="PPSStartDate">@incrementdate(this,@DATEINC)</e>
      <e en="T" t="00400250" n="PPSEndDate">@incrementdate(this,@DATEINC)</e>
      <e en="T" t="30060008" n="StructureSetDate">@incrementdate(this,@DATEINC)</e>

      <!-- To randomize -->
      <e en="T" t="00080050" n="AccessionNumber">@hash(this,16)</e>
      <e en="T" t="00100020" n="PatientID">@hash(this,10)</e>
      <e en="T" t="00100010" n="PatientName">@hashname(this,6,2)</e>
      <e en="T" t="00120040" n="ClinicalTrialSubjectID">@hashptid(@SITEID,PatientID)</e>
      <e en="T" t="00080014" n="InstanceCreatorUID">@hashuid(@UIDROOT,this)</e>
      <e en="T" t="00080018" n="SOPInstanceUID">@hashuid(@UIDROOT,this)</e>
      <e en="T" t="00080058" n="FailedSOPInstanceUIDList">@hashuid(@UIDROOT,this)</e>
      <e en="T" t="0008010d" n="CodeSetExtensionCreatorUID">@hashuid(@UIDROOT,this)</e>
      <e en="T" t="00081155" n="RefSOPInstanceUID">@hashuid(@UIDROOT,this)</e>
      <e en="T" t="00081195" n="TransactionUID">@hashuid(@UIDROOT,this)</e>
      <e en="T" t="00083010" n="IrradiationEventUID">@hashuid(@UIDROOT,this)</e>
      <e en="T" t="00089123" n="CreatorVersionUID">@hashuid(@UIDROOT,this)</e>
      <e en="T" t="0020000d" n="StudyInstanceUID">@hashuid(@UIDROOT,this)</e>
      <e en="T" t="0020000e" n="SeriesInstanceUID">@hashuid(@UIDROOT,this)</e>
      <e en="T" t="00200052" n="FrameOfReferenceUID">@hashuid(@UIDROOT,this)</e>
      <e en="T" t="00200200" n="SynchronizationFrameOfReferenceUID">@hashuid(@UIDROOT,this)</e>
      <e en="T" t="00209161" n="ConcatenationUID">@hashuid(@UIDROOT,this)</e>
      <e en="T" t="00209164" n="DimensionOrganizationUID">@hashuid(@UIDROOT,this)</e>
      <e en="T" t="00281199" n="PaletteColorLUTUID">@hashuid(@UIDROOT,this)</e>
      <e en="T" t="00281214" n="LargePaletteColorLUTUid">@hashuid(@UIDROOT,this)</e>
      <e en="T" t="00404023" n="RefGenPurposeSchedProcStepTransUID">@hashuid(@UIDROOT,this)</e>
      <e en="T" t="0040a124" n="UID">@hashuid(@UIDROOT,this)</e>
      <e en="T" t="0040db0c" n="TemplateExtensionOrganizationUID">@hashuid(@UIDROOT,this)</e>
      <e en="T" t="0040db0d" n="TemplateExtensionCreatorUID">@hashuid(@UIDROOT,this)</e>
      <e en="T" t="0070031a" n="FiducialUID">@hashuid(@UIDROOT,this)</e>
      <e en="T" t="00880140" n="StorageMediaFilesetUID">@hashuid(@UIDROOT,this)</e>
      <e en="T" t="30060024" n="ReferencedFrameOfReferenceUID">@hashuid(@UIDROOT,this)</e>
      <e en="T" t="300600c2" n="RelatedFrameOfReferenceUID">@hashuid(@UIDROOT,this)</e>
      <e en="T" t="300a0013" n="DoseReferenceUID">@hashuid(@UIDROOT,this)</e>

      <r en="T" t="curves">Remove curves</r>
      <r en="T" t="overlays">Remove overlays</r>
      <r en="T" t="privategroups">Remove private groups</r>
      <r en="T" t="unspecifiedelements">Remove unchecked elements</r>
   </script>
